project:
  type: website

website:
  title: "GGPLOT2"
  sidebar:
    contents:
      - href: index.qmd
        text: Home
      - hr1.qmd
      - hr2.qmd
      - hr3.qmd
      - hr4.qmd
      - hr5.qmd
      - hr6.qmd
      - hr7.qmd
      - hr8.qmd
      - ans.qmd
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

